### ISSUE TITLE
What's your pytorch version?

### ISSUE THREAD

**Issue by FatherPrime** [yz-cnsdqz/MOJO-release#2]
Thanks for your great job,
  now i meet the problem about torchgeometry version and torch version when I run python` experiments/test_recursive_proj.py --cfg amass_mojo_f9_nsamp50 --testdata ACCAD --gpu_index 0` . Could u tell me your test env?

Traceback (most recent call last):
  File "experiments/test_recursive_proj.py", line 222, in <module>
    pred_with_proj(n_seqs=60, n_gens=50)
  File "experiments/test_recursive_proj.py", line 101, in pred_with_proj
    prev_pose_vp, prev_handpose)
  File "experiments/test_recursive_proj.py", line 39, in get_prediction
    prev_pose_vp, prev_handpose)
  File "/home/zzj/project/MOJO/models/fittingop.py", line 272, in decode_with_fitting
    y_i.detach())
  File "/home/zzj/project/MOJO/models/fittingop.py", line 209, in fitting_subloop
    loss, verts= self.calc_loss(betas, verts_gt, ss)
  File "/home/zzj/project/MOJO/models/fittingop.py", line 180, in calc_loss
    body_param['global_orient'] = RotConverter.rotmat2aa(RotConverter.cont2rotmat(self.glo_rot_rec))
  File "/home/zzj/project/MOJO/models/fittingop.py", line 64, in rotmat2aa
    pose = tgm.rotation_matrix_to_angle_axis(homogen_matrot).view(-1, 3).contiguous()
  File "/home/zzj/anaconda3/envs/mojo/lib/python3.6/site-packages/torchgeometry/core/conversions.py", line 233, in rotation_matrix_to_angle_axis
    quaternion = rotation_matrix_to_quaternion(rotation_matrix)
  File "/home/zzj/anaconda3/envs/mojo/lib/python3.6/site-packages/torchgeometry/core/conversions.py", line 302, in rotation_matrix_to_quaternion
    mask_c1 = mask_d2 * (1 - mask_d0_d1)
  File "/home/zzj/anaconda3/envs/mojo/lib/python3.6/site-packages/torch/tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

**Comment by yz-cnsdqz** [comment]
thanks for your interests! 
This problem is not caused by version incompatibility, but an internal problem in torchgeometry. As indicated in the error info, you need to jump into "/home/zzj/anaconda3/envs/mojo/lib/python3.6/site-packages/torchgeometry/core/conversions.py" and replace e.g. (1 - mask_d0_d1) with (~mask_d0_d1)

**Comment by FatherPrime** [comment]
Thanks for your reply,
  I had the bug above, but when I try to visualize. I meet some problems. It seems many people meet the similar problems, however it's hard to solve render problem. Could you give me some advice? My open3d version is 0.9.0. Xmanager version is 6

(mojo) video@bcnl-PowerEdge-T640:~/MOJO$ python experiments/vis_kps_amass.py 
-- processing: /home/video/MOJO/results/amass_mojo_f9_nsamp50/results/seq_gen_seed1/ACCAD/results_marker_41.pkl
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "experiments/vis_kps_amass.py", line 132, in <module>
    seq=seq,gen=gen)
  File "experiments/vis_kps_amass.py", line 25, in visualize
    vis.create_window(width=960, height=540,visible=False)
RuntimeError: [Open3D ERROR] GLFW Error: GLX: GLX version 1.3 is required

**Comment by FatherPrime** [comment]
I find that `pred = get_prediction_stats(traj, 'dlow', sample_num=cfg.nk, num_seeds=num_seeds, concat_hist=True)` in line 70 in eval_jts_pred.py, get_prediction_stats  has no define. Do you mean 'get_prediction' in the line 17?

**Comment by yz-cnsdqz** [comment]
for the open3d question, i think it is an open3d problem and you could ask in their repo. You perhaps did not install all dependencies of open3d.
For the second question, probably yes.
